### ISSUE TITLE
存在严重Bug

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-hsyhhssyy-functions-gui#1]
会修改存储在bot中的keywords, 导致调用功能A时转去调用功能B，并且存在跨插件现象，调用插件A的某个功能会被转去调用B插件的功能，

**Comment by hsyhhssyy** [comment]
这个插件不是修改了存储在bot中的keywords，而是用自定义的verify函数替换了每一个插件的每一个message_handler
为了防止这个插件影响别的插件，默认刚刚安装这个插件的时候，所有的功能都是不起效的，如果出现影响到关键词的情况，一定是用户手动开启了什么。

插件定位message_handler的时候用的是代码里的顺序，所以修改代码里handler的顺序可能会调用到其他的插件，所以为了防止这种情况，每次其他插件版本号升级，我都会废弃相关的配置，让他恢复默认。

这个功能我自己测试了一周，没有发现有串插件的情况。
调用功能A时转去调用功能B确实是有可能的，插件如果在同版本号下修改了message_handler的顺序，并且打开了插件里的配置功能，就会导致这个情况。

总之，我在插件先标题里加一个Warning，防止用户在不知道的情况下下载这个插件。

**Comment by wutongshufqw** [comment]
我是啥都没动，就安装该插件重启了一下就出问题了
我用‘兔兔功能’这个指令，反而去调用‘剧情查询’了

**Comment by wutongshufqw** [comment]
![dd3dad1d686245ca6984c42c4ea71468_720](https://user-images.githubusercontent.com/87960738/231512464-05014558-4abd-4728-9f60-edf08c3cf224.jpg)
![f646431180a847dc8fae43de677ee621_720](https://user-images.githubusercontent.com/87960738/231512524-cc6e454c-fb93-43bf-b487-52039c6948e7.jpg)
这里是报错，可以很明显地看到串插件了

**Comment by wutongshufqw** [comment]
嗯，目前我不一定用得到，就是在这里说明一下这个插件存在的一些小问题

**Comment by hsyhhssyy** [comment]
我自己试了好几把，都没办法复现这个问题，我只能开着这个插件再看一段时间。

我强化了一下插件标题的警告，让用户小心下载。
此外加入了一个全局日志开关配置项，显示当前哪个自定义verify函数被执行，哪个自定义verify被跳过，未来如果发现问题可以去纠错，只能这样了。

如果你有时间，可以帮帮忙，更新最新版插件，打开这个开关，然后输入兔兔功能，看看日志里是什么，我也很好奇是哪里的问题。

**Comment by wutongshufqw** [comment]
好的
